import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // In React we used Outlet instead of Children
  return (
    <>
      <div id="header">Logo</div>
      {children}
    </>
  );
}
